#
# dummy_thermo gems configuration file
#
# Format:
#   <configuration name>:
#     <number of month>:
#       max: <maximum temparature of the month>
#       min: <minimum temparature of the month>
#       maxhour: <the hottest hour in a day>
#       minhour: <the coldest hour in a day>
#
# Data type of parameters:
#   * configuration name: string (alphabet, numbers and "_")
#   * number of month: commma separated numbers and ranges
#   * max, min: folat
#   * maxhour, minhour: integer

default:
  1 .. 12:
    max: 25.0
    min: 15.0
    maxhour: 14
    minhour: 5

outdoor:
  1:
    max: 10
    min: -5
    maxhour: 14
    minhour: 6
  3 .. 5, 10:
    max: 20
    min: 5
  7, 8:
    max: 35
    min: 20
    minhour: 4
